[project]
name = "minimal-ltc3350"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "forallpeople>=2.7.1",
    "jupyter>=1.1.1",
    "sympy>=1.14.0",
]
